### ISSUE TITLE
adding datetime for train_dirs

### ISSUE THREAD

**Issue by inkyusa** [UoA-CARES/BuilT#5]
Currently, all trained model and splitted sets are stored under `train_dirs` and maybe overwritten when multiple experiments are conducted. It may be suggested to add datetime (e.g., year, date, time, hours) as suffix of the train_dirs (e.g., `train_dirs/tweet/classification/2020-11-23-13-20/roberta-base/` or similar)

**Comment by jlim262** [comment]
I added the feature to the commit above. I'll add a datetime folder at the end of training folder if you add **use_date** when you run the train script(python run.py train with $INDEX_EXTRACTION_CONFIG -f **use_date=True**)
